Style/StringLiterals:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 21

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Naming/FileName:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.4.3
